version: '3'
services:
  tomcat: 
     image: 'tomcat:9'
     ports: 
      - "8080:8080"
     volumes:
      - '/mnt/war:/usr/local/tomcat/webapps'
  
  tomcat1: 
     image: 'tomcat:9'
     ports: 
      - "8090:8080"
     volumes:
      - '/mnt/war:/usr/local/tomcat/webapps'
    
